version: '3'
services:
  proxy_pool:
    image: ghcr.io/jhao104/proxy_pool:latest
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/9"

  proxy_redis:
    image: redis:7
    container_name: proxy_redis
    command: redis-server
    ports:
      - "6479:6379"